### ISSUE TITLE
Humidity limit

### ISSUE THREAD

**Issue by Davit-Qobuladze** [freeuni-sdp/iot-house-registry#1]
რაღაც ლიმიტი ხო უნდა გვქონდეს რასაც თუ გადასცდა ტენიანობა აბაზანაში, მაშინ ჩავრთავთ აბაზანაში გამწოვს. ეს რიცხვი სახლების შესახებ ინფორმაციას ხო უნდა მოყვებოდეს თუ სად ვნახოთ?

**Comment by gkiko** [comment]
hardcoded გქონდეს

2016-06-25 18:28 GMT+04:00 Davit-Qobuladze notifications@github.com:
