### ISSUE TITLE
Add CORS headers for browser

### ISSUE THREAD

**Issue by ggham** [freeuni-sdp/iot-house-registry#2]
როდესაც სერვისი request-ს მიიღებს ჰედერით "Origin: http://localhost:8080", ან ჰედერით "Origin: http://iot-webui.herokuapp.com", response-ის ჰედერში უნდა დაემატოს სამი ველი:
"Access-Control-Allow-Origin: origin რომელიც request-ის ჰედერით მოვიდა"
"Access-Control-Allow-Methods: POST, GET, PUT, DELETE, OPTIONS"
"Access-Control-Allow-Headers: Content-Type"
იმისთვის, რო ბრაუზერმა დაამუშავოს მიღებული response.

**Comment by gkiko** [comment]
65d4a938d13d829d52318f98ce43af02971c8d9e
