### ISSUE TITLE
სახლების json ფაილში სინტაქსური შეცდომა

### ISSUE THREAD

**Issue by chalagashvili** [freeuni-sdp/iot-house-registry#3]
http://iot-house-registry.herokuapp.com/houses ამ ლინკზე **მეორე** სახლის geo_loc-ში ასეთი ჩანაწერია:
"geo_location":{"_":"12,1234.12,1234"}, **პირველი** სახლისაში კი -"geo_location":{"_":"41.8054853,44.7662745"}.  **მეორე** სახლის ლოკაცია არასწორადაა, უნდა იყოს ასე: 12.1234, 12.1234

**Comment by gkiko** [comment]
შესაძლოე. ზეპირად ვაკეთებდი. გადააკეთე

**Comment by chalagashvili** [comment]
გიო სად გადავაკეთო ეგეც მითხარი ბარემ ;დ

**Comment by gkiko** [comment]
https://app.apiary.io/iothouseregistry/editor გერკვიე :+1:

**Comment by chalagashvili** [comment]
update house - ვცადე და 500 Internal error-ს აგდებს Apiary-ზე. Delete ვცადე, რომ ახლიდან ჩამეგდო სახლი და 404 მოაგდო, no resource found-ო house_id-ად  "a1bc00fb-4724-476a-a553-d65d2c1bac0e" რომ გადავეცი. what to do

**Comment by TMandzu** [comment]
https://iot-house-registry.herokuapp.com/houses  -  მე მგონი არავალიდური კოორდინატებია მითითებული. maps.google.com-ზე ესეთი ადგილი არაა. iot-weather-ის API-ს ტესტირებაზე გვჭირდება რომ ვალიდური იყოს კოორდინატები, ეხლა იჭრება ანუ ჩვენი ტესტები. დავიკიდოთ და აქ გაასწორებთ თუ ჩვენ უნდა შევცვალოთ რამე?

**Comment by gkiko** [comment]
რენდომ რიცხვები ჩავწერე. რაც გაგიხარდება ჩაწერე

```
$ http post iot-house-registry.herokuapp.com/houses name="house #1" cam_ip="1111" geo_location="123.123,123.123" heat_ip="2222" sprinkler_ip="3333" vent_ip="4444"
```

> pip3 install httpie
